### ISSUE TITLE
Docker implementation on MacBook Pro

### ISSUE THREAD

**Issue by ingmanuelalfonso** [RAKWireless/udp-packet-forwarder#12] opened 2023-12-22 17:00 UTC
Hi. I am a new MacBook Pro user and I am trying to implement the whole chirpstack and the udp packet forwarder for my RAK7271 USB Gateway. I already did that on a Linux machine successfully but not with Docker. After running `docker-compose up`   I was looking how to identify my Gateway in the /dev folder and the result is shown in the below image. Then I open the docker-compose.yml to edit the /dev address for the RADIO to be included in the .yml file. After that I run again the `docker-compose up` but no matter the address every time I got  an answer_
```
 Running 1/0
 ✔ Container udp-packet-forwarder  Recreated                                                                       0.0s 
Attaching to udp-packet-forwarder
udp-packet-forwarder  | ERROR: /dev/tty.usbmodem203C33A64E4E1 does not exist
udp-packet-forwarder exited with code 1
```

<img width="546" alt="image" src="https://github.com/RAKWireless/udp-packet-forwarder/assets/5880454/a5f27628-f4aa-488f-a5cf-5c4d8e9881f6">

**Comment by xoseperez** [comment] 2024-02-22 08:42
Hi @ingmanuelalfonso 
Sorry for the late reply.
Can you share the whole `docker-compose.yml` file you are using?

**Comment by ingmanuelalfonso** [comment] 2024-02-23 09:23
Sure, Xose. File attached in zip.

[docker-compose.yml.zip](https://github.com/RAKWireless/udp-packet-forwarder/files/14383578/docker-compose.yml.zip)

**Comment by xoseperez** [comment] 2024-02-26 09:03
Aparently serial passthrough is not working for MacOS (I can't test it myself, sorry). Looks like current approach is to use ser2net to pass the USB stream via a TCP socket. The image then should somehow redirect it back to a UARt port... not sure how to do this yet.

**Comment by xoseperez** [comment] 2024-02-26 10:38
Hello again
@ingmanuelalfonso I have added support for remote concentrators using `ser2net`. This is the usual approach to bypass the Docker Desktop for MacOS limitations.
I tested it on a Linux box. The code is in the master branch but the image is not yet available. If you have the chance to build the image yourself you can give it a try.

**Comment by xoseperez** [comment] 2024-03-18 11:02
I'm closing this issue (the problem is not related to this repo but docker and an option has been provided). Feel free to reopen if you need further assistance.

**Closed as completed by xoseperez** 2024-03-18 11:02 UTC
Labels: enhancement
